name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Trigger on tags that start with 'v'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set VERSION variable
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        else
          echo "VERSION=0.0.0-dev.$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        fi

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore ./SearchWords_ClassLibrary/SearchWords_ClassLibrary.csproj

    - name: Build the project
      run: dotnet build ./SearchWords_ClassLibrary/SearchWords_ClassLibrary.csproj --configuration Release

    - name: Pack the NuGet package
      run: |
        dotnet pack ./SearchWords_ClassLibrary/SearchWords_ClassLibrary.csproj --configuration Release --output ./nupkg /p:PackageVersion=${{ env.VERSION }}

    - name: Publish to NuGet
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push ./nupkg/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
